### ISSUE TITLE
How to get discord token on mobile?

### ISSUE THREAD

**Issue by budchirp** [NoobJsPerson/termux-discord-activity#1]
.

**Comment by NoobJsPerson** [comment]
Disable chrome
Get the yandex browser from the play store
Open this link and login
https://discord.com/channels/@me
And go the site bar delete and paste this
```js
javascript:(function()%7Blocation.reload()%3Bvar%20i%20%3D%20document.createElement('iframe')%3Bdocument.body.appendChild(i)%3Balert(i.contentWindow.localStorage.token)%7D)()
```
Do not click enter click on the first suggestion that has the same text
A popup with your token should pop up screenshot it and use any image to text app to get your token
U might need to test it by launching the nodejs server and waiting for errors and modify the token if any until you get it right
WARNING: you must not give/show your token to anyone or share it online anyone who has it has full control over your account
Credit to this article for providing the method
https://blog.himbeer.me/2019/09/02/updated-2019-finding-out-your-discord-users-token-on-mobile-too/
After that u can enable chrome again if you want

**Comment by budchirp** [comment]
Thanks! Btw, it works on chrome canary too
